import type { Agent } from "@/components/coopwakala/AgentsMap";

// Source-of-truth list migrated from the previously hardcoded agents page.
// Used by scripts/seed-coopwakala-agents.ts to populate the `coopwakala-agents`
// collection, and as a fallback by the public page when the collection is empty.
export const COOPWAKALA_AGENTS: Agent[] = [
  { name: "ARUSHA CO-OPERATIVE UNION LTD", region: "Arusha", district: "Arusha", ward: "Kati", street: "Pangani" },
  { name: "NAVIDA SAVINGS AND CREDIT COOPERATIVE SOCIETY LIMITED", region: "Arusha", district: "Arusha", ward: "Kati", street: "Mrefu" },
  { name: "NGOME SAVINGS AND CREDIT COOPERATIVE SOCIETY LIMITED", region: "Dar Es Salaam", district: "Kinondoni", ward: "Mwenge", street: "Mwenge" },
  { name: "KKKT ARUSHA ROAD SACCOS LTD", region: "Dodoma", district: "Dodoma Mjini", ward: "Kiwanja cha Ndege", street: "Area C" },
  { name: "SHAIDU TWAHIL IBRAHIMU", region: "Dodoma", district: "Dodoma Mjini", ward: "Nzuguni", street: "Nzuguni B" },
  { name: "MBEGA AMCOS", region: "Dodoma", district: "Mpwapwa", ward: "Berege", street: "Berege" },
  { name: "HERIEL ALEN MOSHA", region: "Dodoma", district: "Dodoma Mjini", ward: "Uhuru", street: "Barabara ya Sita" },
  { name: "CHATO COOPERATIVE UNION LIMITED", region: "Geita", district: "Chato", ward: "Chato Kati", street: "Chato Kati" },
  { name: "MBOGWE AND BUKOMBE COOPERATIVE UNION LIMITED", region: "Geita", district: "Mbogwe", ward: "Mbogwe", street: "Mbogwe" },
  { name: "JUHUDI AMCOS", region: "Kagera", district: "Kyerwa", ward: "Kyerwa", street: "Rubwera" },
  { name: "KARAGWE DISTRICT COOPERATIVE UNION LTD", region: "Kagera", district: "Karagwe", ward: "Kayanga", street: "Bomani" },
  { name: "MKOMBOZI AMCOS", region: "Kagera", district: "Karagwe", ward: "Kayanga", street: "Nmb" },
  { name: "LAKE TANGANYIKA COOPERATIVE UNION LIMITED (LATCU)", region: "Katavi", district: "Mpanda", ward: "Kawajesi Ya Madukani", street: "Kawajesi Ya Madukani" },
  { name: "AMANI SAMWEL MPOLA", region: "Kigoma", district: "Kigoma CBD", ward: "Mwanga Kaskazini", street: "Mlole" },
  { name: "KIGOMA TOBACCO GROWERS COOPERATIVE UNION LIMITED", region: "Kigoma", district: "Uvinza", ward: "Nguruka", street: "Majengo" },
  { name: "DEOGRASIASI JOSEPH MASSAWE", region: "Kilimanjaro", district: "Moshi", ward: "Bondeni", street: "Swahili" },
  { name: "KIBOSHO-MWEKA SUNGU RCS", region: "Kilimanjaro", district: "Moshi Vijijini", ward: "Kibosho", street: "Mweka" },
  { name: "MASAMA MULA RCS LTD", region: "Kilimanjaro", district: "Hai", ward: "Masama", street: "Mbweera" },
  { name: "MASAMA ROO AMCOS LTD", region: "Kilimanjaro", district: "Hai", ward: "Romu", street: "Sifigha" },
  { name: "REBECCA HARRY MWANGOKA", region: "Kilimanjaro", district: "Moshi", ward: "Mawenzi", street: "Rengua" },
  { name: "URU KATI MAWELLA RCS LTD", region: "Kilimanjaro", district: "Moshi", ward: "Uru Kusini", street: "Kimantamim Kat" },
  { name: "JASY FINANCE", region: "Kilimanjaro", district: "Moshi", ward: "Korongoni", street: "Viwanda" },
  { name: "ILULU SACCOS", region: "Lindi", district: "Lindi Mjini", ward: "Kitumiki", street: "Uhuru" },
  { name: "LINDI MWAMBAO", region: "Lindi", district: "Lindi Mjini", ward: "Mitwero", street: "Mtaa wa Tan Road" },
  { name: "RUNALI COOPERATIVE UNION LIMITED", region: "Lindi", district: "Nachingwea", ward: "Ugawaji", street: "Ugawaji" },
  { name: "WAKULIMA WA MARA COOPERATIVE UNION (WAMACU) LTD", region: "Mara", district: "Tarime", ward: "Ilebu", street: "Ilebu" },
  { name: "GIDESHA AMCOS LTD", region: "Manyara", district: "Mbulu", ward: "Aidalesti", street: "Simha" },
  { name: "MATUI AMCOS", region: "Manyara", district: "Kiteto", ward: "Matui", street: "Matui" },
  { name: "MWAMKA AMCOS", region: "Manyara", district: "Hanang", ward: "Kateshi", street: "Kateshi" },
  { name: "RIFT VALLEY COOPERATIVE UNION LTD", region: "Manyara", district: "Babati", ward: "Bagara", street: "Ngarenaro" },
  { name: "SITTA KUBAGWA ALPHONCE", region: "Manyara", district: "Kiteto", ward: "Engusero", street: "Engusero" },
  { name: "LULU SACCOS", region: "Mbeya", district: "Mbeya Mjini", ward: "Sisimba", street: "Sowote" },
  { name: "KILOMBERO CANE HARVESTERS COOPERATIVE SOCIETY LIMITED", region: "Morogoro", district: "Kilosa", ward: "Ruhaa", street: "Sokoni" },
  { name: "AISHA KHALIDI MSANGI", region: "Mtwara", district: "Tandahimba", ward: "Tandahimba", street: "Forodhani" },
  { name: "JERAD VICENTI NGUYEJE", region: "Mtwara", district: "Masasi", ward: "Mpindindi", street: "Kibaoni" },
  { name: "MASASI-MTWARA COOPERATIVE UNION LIMITED (MAMCU LTD)", region: "Mtwara", district: "Mtwara Municipal", ward: "—", street: "Bima" },
  { name: "TANDAHIMBA NEWALA COOPERATIVE UNION LIMITED (TANECU LTD)", region: "Mtwara", district: "Tandahimba", ward: "—", street: "—" },
  { name: "TANDAHIMBA NEWALA COOPERATIVE UNION LIMITED (TANECU LTD)", region: "Mtwara", district: "Newala", ward: "Luchingu", street: "Sokoni" },
  { name: "NYANZA COOPERATIVE UNION (1984) LIMITED", region: "Mwanza", district: "Nyamagana", ward: "Nyamagana", street: "Nyamagana" },
  { name: "TUNDURU AGRICULTURAL MARKETING COOPERATIVE UNION LIMITED (TAMCU) LTD", region: "Ruvuma", district: "Tunduru", ward: "Majengo", street: "Kalanje" },
  { name: "SHINYANGA REGION COOPERATIVE UNION (1984) LTD", region: "Shinyanga", district: "Shinyanga Mjini", ward: "Kishapu", street: "Shinyanga Miti Mirefu" },
  { name: "KAHAMA COOPERATIVE UNION LIMITED", region: "Shinyanga", district: "Kahama", ward: "Mongolo", street: "Mongolo" },
  { name: "SIMIYU COOPERATIVE UNION (2018) LTD", region: "Simiyu", district: "Bariadi", ward: "Nyakabindi", street: "Nyakabindi" },
  { name: "SINGIDA FARMERS CO-OPERATIVE UNION LIMITED", region: "Singida", district: "Singida", ward: "Mandewa", street: "Bomani" },
  { name: "SONGWE REGION COOPERATIVE UNION LIMITED", region: "Songwe", district: "Songwe", ward: "Vywawa", street: "Uhuru Street" },
  { name: "FREDRICKERICK AHADI MVIOMBO", region: "Tabora", district: "Tabora Mjini", ward: "Kanyenye", street: "Maua" },
  { name: "HAMISI HUSSEIN KANDEGE", region: "Tabora", district: "Urambo", ward: "Urambo", street: "Vibanda Vya Roma" },
  { name: "IGEMBENSABO COOPERATIVE UNION", region: "Tabora", district: "Igunga", ward: "Igunga", street: "Igunga" },
  { name: "IMALAMAKOYE AGRICULTURAL MARKETING COOPERATIVE SOCIETY", region: "Tabora", district: "Urambo", ward: "Urambo", street: "Imalamakoye C" },
  { name: "MILAMBO COOPERATIVE UNION LIMITED", region: "Tabora", district: "Urambo", ward: "Urambo", street: "Ndorobo" },
  { name: "NTEMBEJE HARUNA BIYEZA", region: "Tabora", district: "Urambo", ward: "Urambo", street: "Vibanda Vya Roma" },
  { name: "MANDELA MKANYALI MSAZI", region: "Tabora", district: "Tabora Mjini", ward: "Kanyenye", street: "Maua" },
  { name: "IJA WORKERS SACCOS LTD", region: "Tanga", district: "Lushoto", ward: "Lushoto", street: "Dochi" },
  { name: "TANGAMANO SAVING AND CREDIT COOPERATIVE SOCIETY LIMITED", region: "Tanga", district: "Tanga Mjini", ward: "Tanga Jiji", street: "Swahili Street" },
];
