// Public whistleblower submission.
// - Uploads any evidence file to the Google Cloud Storage bucket (gs://coopbank-media).
// - Creates a record in the `whistleblower-reports` Payload collection (Compliance
//   triages these in Studio). caseRef is auto-generated by the collection.
// - Best-effort email alert to the confidential mailbox (never blocks submission).
import { NextResponse } from "next/server";
import { Storage } from "@google-cloud/storage";
import { getPayload } from "payload";
import config from "../../../../payload.config";

export const runtime = "nodejs";
export const dynamic = "force-dynamic";

// Form report-type label -> collection category enum (best-effort; original label
// is also preserved in the description so nothing is lost).
const CATEGORY_MAP: Record<string, string> = {
  "Fraud & Financial Crime": "fraud",
  "Corruption & Bribery": "corruption",
  "Regulatory Violations": "compliance",
  "Workplace Misconduct": "harassment",
  "Cybersecurity Threats": "other",
  "Governance Failures": "conflict",
  "Other": "other",
};

export async function POST(req: Request) {
  try {
    const fd = await req.formData();
    const get = (k: string) => String(fd.get(k) ?? "").trim();

    const reportType = get("reportType");
    const subject = get("subject");
    const description = get("description");
    if (!reportType || !subject || !description) {
      return NextResponse.json({ error: "Please fill in report type, subject and description." }, { status: 400 });
    }

    const incidentDate = get("incidentDate");
    const location = get("location");
    const name = get("name");
    const email = get("email");
    const phone = get("phone");

    // 1) Upload evidence to the PRIVATE whistleblower bucket (public access prevented).
    //    We store the gs:// path only — never a public URL. Compliance retrieves it
    //    via a short-lived signed URL from Studio (see /api/studio/whistleblower/evidence).
    const evidencePaths: string[] = [];
    const file = fd.get("file");
    if (file instanceof File && file.size > 0) {
      const bucket = process.env.WHISTLEBLOWER_BUCKET || "coopbank-whistleblower";
      const storage = new Storage({ projectId: process.env.GCS_PROJECT_ID || "sakura-group-482908" });
      const safe = file.name.replace(/[^a-zA-Z0-9._-]/g, "_");
      const objectName = `evidence/${Date.now().toString(36)}-${safe}`;
      const buf = Buffer.from(await file.arrayBuffer());
      await storage.bucket(bucket).file(objectName).save(buf, {
        contentType: file.type || "application/octet-stream",
        // private: bucket has uniform access + public-access-prevention enforced
      });
      // Store a Studio-only proxy link (works only for authenticated Compliance users)
      evidencePaths.push(`/api/studio/whistleblower/evidence?path=${encodeURIComponent(`gs://${bucket}/${objectName}`)}`);
    }

    // 2) Compose description (preserve location, original report-type label, evidence refs)
    let fullDescription = description;
    if (location) fullDescription += `\n\nLocation / Department: ${location}`;
    fullDescription += `\n\nReport type (selected): ${reportType}`;
    if (evidencePaths.length) fullDescription += `\n\nEvidence file(s) — private, view in Studio (Compliance only):\n${evidencePaths.join("\n")}`;

    const anonymous = !(name || email || phone);

    // 3) Create the report in Payload
    const payload = await getPayload({ config });
    const doc = await payload.create({
      collection: "whistleblower-reports",
      overrideAccess: true,
      data: {
        category: CATEGORY_MAP[reportType] || "other",
        subject,
        description: fullDescription,
        ...(incidentDate ? { incidentDate: new Date(incidentDate).toISOString() } : {}),
        reporter: {
          anonymous,
          ...(name ? { name } : {}),
          ...(email ? { email } : {}),
          ...(phone ? { phone } : {}),
          preferredContact: email ? "email" : phone ? "phone" : "none",
        },
      },
    });

    const caseRef = (doc as { caseRef?: string }).caseRef ?? "";

    // 4) Best-effort ALERT-ONLY email — deliberately contains NO report content,
    //    reporter identity, or evidence. Sensitive data stays in the access-controlled
    //    Payload collection; the email only nudges Compliance to review in Studio.
    if (process.env.RESEND_API_KEY) {
      try {
        await fetch("https://api.resend.com/emails", {
          method: "POST",
          headers: { Authorization: `Bearer ${process.env.RESEND_API_KEY}`, "Content-Type": "application/json" },
          body: JSON.stringify({
            from: "CoopBank Whistleblower <noreply@sakuragroup.co.tz>",
            to: ["whistleblow@cbtbank.co.tz"],
            subject: `New whistleblower report awaiting review — ${caseRef}`,
            html: `<div style="font-family:sans-serif">
              <h3>A new confidential report has been submitted</h3>
              <p>Reference <b>${caseRef}</b> is awaiting triage.</p>
              <p>For confidentiality, no report details are included in this email.
              Please review it in <b>Studio → Compliance → Whistleblower Reports</b>.</p>
            </div>`,
          }),
        });
      } catch (mailErr) {
        console.error(`[WHISTLEBLOWER] notification email failed for ${caseRef}`, mailErr);
      }
    }

    return NextResponse.json({ success: true, caseRef });
  } catch (err) {
    console.error("[WHISTLEBLOWER] Error:", err);
    return NextResponse.json({ error: "Something went wrong submitting your report. Please try the confidential email instead." }, { status: 500 });
  }
}
